CREATE SCHEMA IF NOT EXISTS `proyectop312023` DEFAULT CHARACTER SET utf8 ;
USE `proyectop312023`;


CREATE TABLE IF NOT EXISTS tbl_usuario (
	marcaid INT NOT NULL AUTO_INCREMENT,
	marcanombre VARCHAR(45) NOT NULL,
	marcaestatus VARCHAR(25) NOT NULL,
	PRIMARY KEY (marcaid) )
ENGINE = InnoDB CHARACTER SET = latin1;
